package com.pessoto.stockmarket.core.presentation.theme

import androidx.compose.ui.graphics.Color

// Colors for light mode
val LightPrimary = Color(0xFF128C7E)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFB2DFDB)
val LightOnPrimaryContainer = Color(0xFF004D40)
val LightInversePrimary = Color(0xFF80CBC4)
val LightSecondary = Color(0xFF25D366)
val LightOnSecondary = Color(0xFF000000)
val LightSecondaryContainer = Color(0xFFC8E6C9)
val LightOnSecondaryContainer = Color(0xFF1B5E20)
val LightTertiary = Color(0xFF03A9F4)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFB3E5FC)
val LightOnTertiaryContainer = Color(0xFF01579B)
val LightBackground = Color(0xFFFFFFFF)
val LightOnBackground = Color(0xFF000000)
val LightSurface = Color(0xFFECE5DD)
val LightOnSurface = Color(0xFF000000)
val LightSurfaceVariant = Color(0xFFEEEEEE)
val LightOnSurfaceVariant = Color(0xFF616161)
val LightSurfaceTint = LightPrimary
val LightInverseSurface = Color(0xFF303030)
val LightInverseOnSurface = Color(0xFFECE5DD)
val LightError = Color(0xFFB00020)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFCDD2)
val LightOnErrorContainer = Color(0xFFB71C1C)
val LightOutline = Color(0xFFBDBDBD)
val LightOutlineVariant = Color(0xFF757575)
val LightScrim = Color(0xFF000000)

// Colors for dark mode
val DarkPrimary = Color(0xFF128C7E)
val DarkOnPrimary = Color(0xFFFFFFFF)
val DarkPrimaryContainer = Color(0xFF004D40)
val DarkOnPrimaryContainer = Color(0xFFB2DFDB)
val DarkInversePrimary = Color(0xFF80CBC4)
val DarkSecondary = Color(0xFF075E54)
val DarkOnSecondary = Color(0xFFFFFFFF)
val DarkSecondaryContainer = Color(0xFF1B5E20)
val DarkOnSecondaryContainer = Color(0xFFC8E6C9)
val DarkTertiary = Color(0xFF0288D1)
val DarkOnTertiary = Color(0xFFFFFFFF)
val DarkTertiaryContainer = Color(0xFF01579B)
val DarkOnTertiaryContainer = Color(0xFFB3E5FC)
val DarkBackground = Color(0xFF1F2C34)
val DarkOnBackground = Color(0xFFECE5DD)
val DarkSurface = Color(0xFF2C3E50)
val DarkOnSurface = Color(0xFFECE5DD)
val DarkSurfaceVariant = Color(0xFF424242)
val DarkOnSurfaceVariant = Color(0xFFBDBDBD)
val DarkSurfaceTint = DarkPrimary
val DarkInverseSurface = Color(0xFFECE5DD)
val DarkInverseOnSurface = Color(0xFF303030)
val DarkError = Color(0xFFCF6679)
val DarkOnError = Color(0xFF000000)
val DarkErrorContainer = Color(0xFFB71C1C)
val DarkOnErrorContainer = Color(0xFFFFCDD2)
val DarkOutline = Color(0xFF757575)
val DarkOutlineVariant = Color(0xFFBDBDBD)
val DarkScrim = Color(0xFF000000)
